#ifndef HONPR_CHARACTER_LILTOON_SOURCE_ASSEMBLY_INCLUDED
#define HONPR_CHARACTER_LILTOON_SOURCE_ASSEMBLY_INCLUDED

#define HONPR_HAS_ALPHA_CLIP_POLICY 1
#define HONPR_HAS_BASE_COLOR_TEXTURE 1
#define HONPR_HAS_HORP_SHADOW_RECEIVER 1
#define HONPR_HAS_INDIRECT_LIGHT 1
#define HONPR_HAS_LILTOON_BACKFACE_COLOR 1
#define HONPR_HAS_LILTOON_BACKLIGHT 1
#define HONPR_HAS_LILTOON_DIFFUSE_RAMP 1
#define HONPR_HAS_LILTOON_DISTANCE_FADE 1
#define HONPR_HAS_LILTOON_EMISSION_PRIMARY 1
#define HONPR_HAS_LILTOON_EMISSION_SECONDARY 1
#define HONPR_HAS_LILTOON_GLITTER 1
#define HONPR_HAS_LILTOON_MATCAP 1
#define HONPR_HAS_LILTOON_OUTLINE 1
#define HONPR_HAS_LILTOON_RIM_LIGHT 1
#define HONPR_HAS_LILTOON_RIM_SHADE 1
#define HONPR_HAS_LILTOON_SECONDARY_MATCAP 1
#define HONPR_HAS_LILTOON_SPECULAR 1
#define HONPR_HAS_MATERIAL_SEMANTICS 1
#define HONPR_HAS_NORMAL_MAP 1
#define HONPR_HAS_OIT_ACCUMULATION 1
#define HONPR_HAS_REGION_MASK 1
#define HONPR_HAS_SCREEN_AO_RECEIVER 1
#define HONPR_HAS_SEMANTIC_MAP 1
#define HONPR_HAS_SCREEN_SPACE_SSS_SOURCE 1
#define HONPR_HAS_STANDARD_AOV 1
#define HONPR_HAS_STYLE_RAMP_ATLAS 1
#define HONPR_HAS_TRANSPARENT_COMPOSITE 1
#define HONPR_HAS_URP_MAIN_LIGHT 1

#include "HoNprCharacterLilToonShared.hlsl"

#endif
